services:
  scenarioService:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/scenarioService/src           # Mount the local src directory
      - ./target:/scenarioService/target       # Mount the local target directory
      - ./mvnw:/scenarioService/mvnw           # Mount the mvnw script
      - ./pom.xml:/scenarioService/pom.xml     # Mount the pom.xml if needed
    ports:
      - "8093:8093"                     # Map port 8091 to the host