services:
  scenario:
    container_name: scenarioService-test
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/scenarioService/src
      - ./target:/scenarioService/target
      - ./mvnw:/scenarioService/mvnw
      - ./pom.xml:/scenarioService/pom.xml
    ports:
      - "8084:8084"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: dev
    networks: 
      - babymonitor