services:
  scenario:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/scenarioService/src           # Mount the local src directory
      - ./target:/scenarioService/target       # Mount the local target directory
      - ./mvnw:/scenarioService/mvnw           # Mount the mvnw script
      - ./pom.xml:/scenarioService/pom.xml     # Mount the pom.xml if needed
    ports:
      - "8084:8084"                     # Map port 8091 to the host
    env_file:
      - .env.properties
    environment:
      SPRING_PROFILES_ACTIVE: dev